dist: trusty
sudo: false

language: cpp

compiler:
  - gcc

python:
  - 3.6

branches:
  only:
    # only trigger CI on dev branch
    - testing

before_install:
  # activate out of the box python 3.6 environement
  - source ~/virtualenv/python3.6/bin/activate

install:
  - python --version
  # Install project requirements and test requirements
  - pip install -r ./requirements.txt
  - pip install -r ./requirements-test.txt
  # Load SimulationCraft
  - git clone https://github.com/simulationcraft/simc.git SimulationCraft
  - cd SimulationCraft/engine
  # Build SimulationCraft executable
  - make optimized
  - cp simc ..
  - cd ..
  - chmod +x simc
  - cd ..

script:
  # Test simulation_objects and collect coverage information at the same time
  - coverage run --source=bloodytools/simulation_objects --omit=*_tests.py ./bloodytools/simulation_objects/simulation_objects_tests.py

before_script:
  # Save values for discord notifactions
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
  - export PYTHON_VERSION="$(python --version)"

after_success:
  # Send notification to discord
  - chmod +x success.sh
  - ./success.sh
  - coveralls

after_failure:
  # Send notification to discord
  - chmod +x fail.sh
  - ./fail.sh

notifications:
  # Deactivate email notifications
  email: false
